NAME interrupts

EXTRN CODE (PJMP_MAIN, PJMPI_DETECT_BAUDRATE_ISR, PJMPI_REFRESH_SCREEN, PJMPI_TIMER_1_ISR, PJMPI_KEYBOARD_ISR)

; ISR_RESET
CSEG AT 0x0000
    JMP PJMP_MAIN

; ISR_EXTERN_0
CSEG AT 0x0003
    JMP PJMPI_DETECT_BAUDRATE_ISR

; ISR_TIMER_0
CSEG AT 0x000B
    JMP PJMPI_REFRESH_SCREEN

; ISR_EXTERN_1
CSEG AT 0x0013
    RETI

; ISR_TIMER_1
CSEG AT 0x001B
    JMP PJMPI_TIMER_1_ISR

; ISR_SERIAL
CSEG AT 0x0023
    JMP PJMPI_KEYBOARD_ISR

; ISR_TIMER_2
CSEG AT 0x002B
    RETI

END
