SET C51INC=D:\Programme\Keil\C51\INC\Atmel\;D:\Programme\Keil\C51\INC\
SET C51LIB=D:\Programme\Keil\C51\LIB
SET CPU_TYPE=AT89C52
SET CPU_VENDOR=Atmel
SET UV2_TARGET=Assembly Target
SET CPU_XTAL=0x016E3600
D:\Programme\Keil\C51\BIN\A51.EXE @DISP~LMS._IA
D:\Programme\Keil\C51\BIN\A51.EXE @blinky._ia
D:\Programme\Keil\C51\BIN\A51.EXE @ram_test._ia
D:\Programme\Keil\C51\BIN\BL51.EXE @Blinky.lnp
"D:\Programme\Keil\C51\BIN\OH51.EXE" "Blinky" 
